parameters:
  - name: availabilityZone
    type: string
    default: SC

variables:
  - template: variables-common.yml

  # file name in variables for debugging yaml
  - name: variableTemplateFile
    value: 'caller variables-dev.yml'

  # add environment-specific variables here

  - name: ingressEnvironment
    value: 'dev'
