parameters:
  - name: availabilityZone
    type: string
    default: SC

variables:
  - template: variables-common.yml

  # file name in variables for debugging yaml
  - name: variableTemplateFile
    value: 'caller variables-development.yml'

  # add environment-specific variables here
  - name: environment
    value: 'development'

  - name: ingressEnvironment
    value: 'development'
