### Implementation Instructions ###
# 1. If you have not already done so, create a DevOps folder at the root of your code repository
# 2. In that folder, create another folder that will be the devops name of your deployable. this will coordinate
#    with your docker image name and your helm release name. e.g. connect-api, caerus-import-manager, hermes-message-sender
# 3. Copy this file to the root of the deployable folder, ensuring it is named build.yml
# 4. Find each TODO in this file and follow the instructions to provide the appropriate value for your deployable.

### Semantic Version ###
# This value represents the version of the build.
# The recommended format is to keep it in line with the devops-templates versioning. this will allow for scripted updates in the future.
# See the ref property on the loyal-templates repository in the resources section for that value.
name: '1.3.$(Rev:r)$(BuildSuffix)'

### Build Parameters ###
# Allows the use of non-default values in the event of a manually invoked build
parameters:
  # Specifies whether to perform a dry run of the pipeline.
  # When set to `true`, the pipeline executes the build and any optional testing steps, but does not publish images/artifacts.
  # This value overrides the isForcePush parameter. Artifacts will never be pushed when isDryRun is set to `true`.
  # This can be useful for testing the pipeline and running tests without making the output available to be deployed.
  - name: isDryRun
    type: boolean
    displayName: Perform a dry run - do not push the docker image
    default: false

    # Determines whether to push docker images and artifacts regardless of the branch being built.
    # When set to `true`, docker images/artifacts will be published even if the build is not on a protected deployment branch.
    # This value is overridden by the isDryRun parameter.
    # This can be useful in the event a deployment is required from a non-standard branch.
  - name: isForcePush
    type: boolean
    displayName: Force push the docker image to the acr, even on a non-standard build
    default: false

### CI Triggers ###
# Provides rules for the branch and source control events that will trigger the build.
# https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
trigger:
  branches:
    include:
      - refs/heads/master
      - refs/heads/develop
      - refs/heads/release/*
  paths:
    exclude:
      - 'DevOps/**/deploy.yml'
      - 'DevOps/**/values.yaml'
      - 'doc'
      - '*.md'
      - '*.ps*1'

### PR Triggers ###
# Provides rules for the pull request events that will trigger the build.
# https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers
pr:
  branches:
    include:
      - refs/heads/master
      - refs/heads/develop
      - refs/heads/release/*
  paths:
    exclude:
      - 'DevOps/**/deploy.yml'
      - 'DevOps/**/values.yaml'
      - 'doc'
      - '*.md'
      - '*.ps*1'

### Pipeline Resources ###
# This section specifies the service connection details needed for using any external resources, namely the loyalhealth/devops-templates repository.
# This should reference the shared github connection that has been shared with each Azure DevOps project.
resources:
  repositories:
    - repository: loyal-templates
      type: github
      name: loyalhealth/devops-templates
      ref: releases/v1.3
      # TODO:    update to the name of the shared github connection service connection in the Azure DevOps project.
      #          the suffix should be the name of the azure devops project.
      # EXAMPLE: github-connection-ConnectApi
      endpoint: github-connection-boxserver

### Template Extensions ###
# Each build pipeline should extend a loyal template that standardizes the build process.
# For details on the available templates, see the devops-templates repository.
extends:
  template: build_dotnet-application.yml@loyal-templates
  parameters:
    # TODO:    update to the path of where the deployable's DevOps files are located
    # EXAMPLE: ./DevOps/connect-api
    devOpsRootPath: ./DevOps/boxserver-api
    isDryRun: ${{ parameters.isDryRun }}
    isForcePush: ${{ parameters.isForcePush }}
